Iter9 to main
Dreeedy/shorturl pull request #13
Opened 2024-12-23 15:51 UTC by Dreeedy

2024-12-24 18:02 UTC, Dreeedy commented
Застрял на том, что когда я пытаюсь пофиксить замечания линтера в package gzip и начинаю обрабатывать c.zw.Write(p) или c.zw.Close() и тд, то я перестаю проходить тесты по непонятным причинам. По сути передаются все те же данные.

2024-12-27 12:50 UTC, s-shpak requested changes

2024-12-27 12:50 UTC, s-shpak commented on internal/config/config.go
> +	// currentDir, err := os.Getwd()
deadcode

2024-12-27 12:50 UTC, s-shpak commented on internal/handlers/handlers.go
> +const messageInternalServerEroror string = "Internal Server Error"
```suggestion
const messageInternalServerError string = "Internal Server Error"
```

2024-12-27 12:50 UTC, s-shpak commented on internal/handlers/handlers.go
> +			http.Error(w, messageInternalServerEroror, http.StatusInternalServerError)
Вместо константы ты можешь использовать здесь https://pkg.go.dev/net/http#StatusText

2024-12-27 12:50 UTC, s-shpak commented on internal/handlers/handlers_test.go
> +	ctrl := gomock.NewController(t)
Контроллер лучше создавать для каждого теста отдельно: так ты будешь уверен, что тесты изолированы друг от друга

2024-12-27 12:50 UTC, s-shpak commented on internal/handlers/handlers_test.go
> +			log.Printf("TestShorten.resBody: %s", string(resBody))
В тестах для логирования лучше использовать https://pkg.go.dev/testing#T.Log

2024-12-27 12:50 UTC, s-shpak commented on internal/middlewares/gzip/gzipmiddleware.go
> +		log.Printf("gzip.Reader.Read: %v", err)
Если ты используешь кастомный логгер, то не используй log в коде. Его использование оправдано только если ты логируешь что-то до инициализации кастомного логгера.

2024-12-27 12:50 UTC, s-shpak commented on internal/services/zaplogger/zaplogger.go
> +type Logger interface {
Я не советую оборачивать логгер в новую структуру/интерфейс. Это:
1. усложняет код
2. ограничивает тебя в использовании всего функционала, который предоставляет логгер

Практика показывает, что лучше использовать логгер напрямую, как структуру из стороннего пакета.

2024-12-27 12:50 UTC, s-shpak commented on internal/storages/filestorage/filestorage.go
> +type Storage interface {
м спринте мы добавляем обособленную часть функционала к хранилищу: запись в файл. То есть новый тип хранилища полностью повторяет функционал MemoryStore и расширяет его. Но мы оставляем возможность запустить сервис без записи в файл. Потому кажется логичным не удалять существующую структуру, и не дуплицировать функционал, а написать обертку над MemoryStore.

Для этого можно использовать композицию и встроить MemoryStore в новую структуру FileStore. При вызове сохранения, например, новая структура будет вызывать вначале добавление новой записи в память (через встроенный объект), а потом сохранение в файл.

В этом случае убедись, что ты выполняешь инициализацию нужного типа при старте сервиса (можно использовать паттерн Factory, как разбирали на первом вебинаре).

При этом кажется, что интерфейс у `MemoryStore` и `FileStore` должны совпадать: т.е. `LoadFromFile` и `AppendToFile` -- просто внутренние детали реализации хранилища

2024-12-27 12:50 UTC, s-shpak commented on internal/storages/filestorage/filestorage.go
> +		log.Fatalf("Failed to load URLs from file: %v", err)
Фаталиться в глубине кода нельзя

2024-12-27 12:50 UTC, s-shpak commented on internal/storages/filestorage/filestorage.go
> +	_, err := os.Stat(filePath)
Вызов этой функции для проверки существования файла не имеет смысла: во время вызова файл может существовать, а сразу после быть удален, так что попытка записи или чтения не будут иметь смысла.

Работай с файлом напрямую, а возвращаемые ошибки будут индикаторами существования файла.

2025-01-05 08:26 UTC, Dreeedy commented on internal/config/config.go
> +	// currentDir, err := os.Getwd()
Поправил.

2025-01-05 08:28 UTC, Dreeedy commented on internal/handlers/handlers.go
> +const messageInternalServerEroror string = "Internal Server Error"
Поправил.

2025-01-05 08:35 UTC, Dreeedy commented on internal/handlers/handlers.go
> +			http.Error(w, messageInternalServerEroror, http.StatusInternalServerError)
Поправил.

2025-01-05 08:51 UTC, Dreeedy commented on internal/handlers/handlers_test.go
> +	ctrl := gomock.NewController(t)
Поправил.

2025-01-05 08:56 UTC, Dreeedy commented on internal/handlers/handlers_test.go
> +			log.Printf("TestShorten.resBody: %s", string(resBody))
Поправил.

2025-01-06 07:49 UTC, Dreeedy commented on internal/services/zaplogger/zaplogger.go
> +type Logger interface {
Поправил.

2025-01-06 07:58 UTC, Dreeedy commented on internal/storages/filestorage/filestorage.go
> +	_, err := os.Stat(filePath)
Поправил.

2025-01-06 08:20 UTC, Dreeedy commented on internal/storages/filestorage/filestorage.go
> +		log.Fatalf("Failed to load URLs from file: %v", err)
Поправил.

2025-01-06 09:01 UTC, Dreeedy commented on internal/middlewares/gzip/gzipmiddleware.go
> +		log.Printf("gzip.Reader.Read: %v", err)
Поправил.

Правильно понял, что нужно во всем коде, где есть возможность, следует использовать мой кастомный логгер zaplogger?

2025-01-06 13:12 UTC, Dreeedy commented on internal/storages/filestorage/filestorage.go
> +type Storage interface {
Поправил.

Странно, что это было неочевидно из задания инкремента.

2025-01-07 11:39 UTC, s-shpak commented on internal/middlewares/gzip/gzipmiddleware.go
> +		log.Printf("gzip.Reader.Read: %v", err)
Да, все верно: смысл в том, что его можно настроить так, как тебе хочется (формат, доп. информация и т.п.) + с его помощью проще формировтаь структурированные логи.

Этот комментарий можно зарезолвить

2025-01-07 11:40 UTC, s-shpak requested changes

2025-01-07 11:40 UTC, s-shpak commented on cmd/shortener/main.go
> +	newZapLogger, _ := zaplogger.NewZapLogger(newConfig)
Ошибки надо проверять всегда

2025-01-08 05:47 UTC, Dreeedy commented on internal/middlewares/gzip/gzipmiddleware.go
> +		log.Printf("gzip.Reader.Read: %v", err)
Спасибо.

2025-01-08 05:55 UTC, Dreeedy commented on cmd/shortener/main.go
> +	newZapLogger, _ := zaplogger.NewZapLogger(newConfig)
Поправил.

2025-01-08 09:23 UTC, s-shpak approved these changes

2025-01-08 10:01 UTC, merged